version: '3.8'

services:
  helloworld:
    build:
      context: .
    container_name: hello
    volumes:
      - /opt/HelloWorld/prometheus/log:/opt/HelloWorld/prometheus/log
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /opt/HelloWorld/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    volumes:
      - ./:/mnt/config
    ports:
      - "3100:3100"
    command:
      - "-config.file=/mnt/config/loki-config.yaml"

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - ./:/mnt/config
      - /opt/HelloWorld/prometheus/log:/opt/HelloWorld/prometheus/log
    depends_on:
      - loki
    command:
      - "-config.file=/mnt/config/promtail-config.yaml"
