auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  max_chunk_age: 1h

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /var/lib/loki/data/index
    cache_location: /var/lib/loki/data/boltdb-cache
    shared_store: filesystem
  filesystem:
    directory: /var/lib/loki/data/chunks

limits_config:
  enforce_metric_name: false

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

compactor:
  # Compactor enabled configuration in Loki v2.7+
  compaction_retention_duration: 30d  # Keep logs for 30 days
  compaction_work_dir: /var/lib/loki/compactor
  compaction_block_size: 104857600  # 100MB per block
  compaction_index_dir: /var/lib/loki/compaction-index
