auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  max_chunk_age: 1h

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /var/lib/loki/data/index
    cache_location: /var/lib/loki/data/boltdb-cache
    shared_store: filesystem
  filesystem:
    directory: /var/lib/loki/data/chunks

limits_config:
  enforce_metric_name: false

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

# Add compactor configuration
compactor:
  compaction_retention: 30d  # Retain logs for 30 days before compaction
  compaction_work_dir: /var/lib/loki/data/compactor  # Directory where compaction happens
  shared_store: filesystem  # Use filesystem for shared store
  data_dir: /var/lib/loki/data/compactor  # Directory where compactor stores data
  compaction_blocks: 128  # Number of blocks to compact at once
  compaction_frequency: 30m  # Compaction runs every 30 minutes
